import SwiftUI
import shared

/// Bridges the KMP `AssistantViewModel.state` StateFlow into a SwiftUI
/// observable. The ViewModel itself lives in `shared/commonMain`.
final class AssistantBridge: ObservableObject {
    @Published var phaseDescription: String = "Idle"
    @Published var transcript: String = ""
    @Published var reply: String = ""
    @Published var errorText: String? = nil

    let viewModel: AssistantViewModel

    init() {
        let baseUrl = Bundle.main.object(forInfoDictionaryKey: "BASE_URL") as? String ?? "http://localhost:8000"
        let apiKey  = Bundle.main.object(forInfoDictionaryKey: "API_KEY")  as? String ?? ""

        let client = JarvisClient(baseUrl: baseUrl, apiKey: apiKey, httpEngineFactory: { JarvisClientKt.defaultHttpClient() })
        let ws     = JarvisWebSocket(baseUrl: baseUrl, apiKey: apiKey, httpEngineFactory: { JarvisClientKt.defaultHttpClient() })

        self.viewModel = AssistantViewModel(
            client: client,
            ws: ws,
            recorder: AudioRecorder(),
            player: AudioPlayer(),
            sessionId: "ios-\(Int(Date().timeIntervalSince1970))"
        )

        // Observe StateFlow via a Kotlin coroutine collector exposed to Swift.
        // FlowCollector here is a simple bridge type generated by KMP plugins.
        Task { @MainActor in
            for await stateAny in viewModel.state.toAsyncSequence() {
                guard let s = stateAny as? AssistantState else { continue }
                self.phaseDescription = s.phase.name
                self.transcript = s.transcript
                self.reply = s.reply
                self.errorText = s.error
            }
        }
    }

    func sendText(_ text: String) { viewModel.sendText(text: text) }
    func startVoice() { viewModel.startVoiceTurn() }
    func stopVoice() { viewModel.stopVoiceTurn() }
}

struct ContentView: View {
    @StateObject private var bridge = AssistantBridge()
    @State private var draft: String = ""

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Jarvis").font(.largeTitle).bold()
            Text("State: \(bridge.phaseDescription)").foregroundStyle(.secondary)

            TextField("Type a command", text: $draft)
                .textFieldStyle(.roundedBorder)

            Button("Send") {
                let t = draft.trimmingCharacters(in: .whitespaces)
                guard !t.isEmpty else { return }
                bridge.sendText(t)
                draft = ""
            }.buttonStyle(.borderedProminent)

            Button(bridge.phaseDescription == "Listening" ? "Stop" : "Hold to speak") {
                bridge.phaseDescription == "Listening" ? bridge.stopVoice() : bridge.startVoice()
            }.buttonStyle(.bordered)

            if !bridge.transcript.isEmpty { Text("You: \(bridge.transcript)") }
            if !bridge.reply.isEmpty      { Text("Jarvis: \(bridge.reply)") }
            if let err = bridge.errorText { Text("Error: \(err)").foregroundStyle(.red) }

            Spacer()
        }
        .padding()
    }
}
